export type stockDataType = {
  "Tolerance": number;
  "Nigerian Stocks": number;
  "Foreign Stocks": number;
  "Tech Stocks": number;
  "Emerging Stocks": number;
  "Nigerian Bonds": number;
  "Foreign Bonds": number;
  "Commodities": number;
  "Real Estate": number;
  "T-Bills": number;
  "Alternative": number;
};

export const stockData: stockDataType[] = [
  {
    "Tolerance": 0,
    "Nigerian Stocks": 18,
    "Foreign Stocks": 4,
    "Tech Stocks": 2,
    "Emerging Stocks": 7,
    "Nigerian Bonds": 35,
    "Foreign Bonds": 15,
    "Commodities": 7,
    "Real Estate": 12,
    "T-Bills": 0,
    "Alternative": 0,
  },
  {
    "Tolerance": 1,
    "Nigerian Stocks": 20,
    "Foreign Stocks": 5,
    "Tech Stocks": 2,
    "Emerging Stocks": 7,
    "Nigerian Bonds": 35,
    "Foreign Bonds": 6,
    "Commodities": 12,
    "Real Estate": 12,
    "T-Bills": 0,
    "Alternative": 0,
  },
  {
    "Tolerance": 2,
    "Nigerian Stocks": 23,
    "Foreign Stocks": 5,
    "Tech Stocks": 4,
    "Emerging Stocks": 7,
    "Nigerian Bonds": 35,
    "Foreign Bonds": 14,
    "Commodities": 12,
    "Real Estate": 0,
    "T-Bills": 0,
    "Alternative": 0,
  },
  {
    "Tolerance": 3,
    "Nigerian Stocks": 26,
    "Foreign Stocks": 6,
    "Tech Stocks": 4,
    "Emerging Stocks": 7,
    "Nigerian Bonds": 35,
    "Foreign Bonds": 10,
    "Commodities": 12,
    "Real Estate": 0,
    "T-Bills": 0,
    "Alternative": 0,
  },

  {
    "Tolerance": 4,
    "Nigerian Stocks": 29,
    "Foreign Stocks": 7,
    "Tech Stocks": 5,
    "Emerging Stocks": 6,
    "Nigerian Bonds": 35,
    "Foreign Bonds": 6,
    "Commodities": 12,
    "Real Estate": 0,
    "T-Bills": 0,
    "Alternative": 0,
  },
  {
    "Tolerance": 5,
    "Nigerian Stocks": 31,
    "Foreign Stocks": 8,
    "Tech Stocks": 6,
    "Emerging Stocks": 5,
    "Nigerian Bonds": 35,
    "Foreign Bonds": 3,
    "Commodities": 12,
    "Real Estate": 0,
    "T-Bills": 0,
    "Alternative": 0,
  },
  {
    "Tolerance": 6,
    "Nigerian Stocks": 35,
    "Foreign Stocks": 8,
    "Tech Stocks": 7,
    "Emerging Stocks": 3,
    "Nigerian Bonds": 35,
    "Foreign Bonds": 12,
    "Commodities": 0,
    "Real Estate": 0,
    "T-Bills": 0,
    "Alternative": 0,
  },
  {
    "Tolerance": 7,
    "Nigerian Stocks": 45,
    "Foreign Stocks": 13,
    "Tech Stocks": 12,
    "Emerging Stocks": 7,
    "Nigerian Bonds": 23,
    "Foreign Bonds": 0,
    "Commodities": 0,
    "Real Estate": 0,
    "T-Bills": 0,
    "Alternative": 0,
  },
  {
    "Tolerance": 8,
    "Nigerian Stocks": 45,
    "Foreign Stocks": 15,
    "Tech Stocks": 15,
    "Emerging Stocks": 9,
    "Nigerian Bonds": 16,
    "Foreign Bonds": 0,
    "Commodities": 0,
    "Real Estate": 0,
    "T-Bills": 0,
    "Alternative": 0,
  },
  {
    "Tolerance": 9,
    "Nigerian Stocks": 45,
    "Foreign Stocks": 18,
    "Tech Stocks": 17,
    "Emerging Stocks": 11,
    "Nigerian Bonds": 9,
    "Foreign Bonds": 0,
    "Commodities": 0,
    "Real Estate": 0,
    "T-Bills": 0,
    "Alternative": 0,
  },
  {
    "Tolerance": 10,
    "Nigerian Stocks": 45,
    "Foreign Stocks": 20,
    "Tech Stocks": 19,
    "Emerging Stocks": 14,
    "Nigerian Bonds": 2,
    "Foreign Bonds": 0,
    "Commodities": 0,
    "Real Estate": 0,
    "T-Bills": 0,
    "Alternative": 0,
  },
];
